---
name: Check Java Code
on:
  pull_request:
  workflow_dispatch:
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check Code Formatting
        run: |
          pushd scheduler
            curl -LJO "https://github.com/google/google-java-format/releases/download/v$GOOGLE_JAR_VERSION/$GOOGLE_JAR_NAME"
            java \
              --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
              --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
              --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
              --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
              --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
              -jar $GOOGLE_JAR_NAME \
              -n --skip-javadoc-formatting \
              **/*.java
          popd
        env:
          GOOGLE_JAR_VERSION: 1.11.0
          GOOGLE_JAR_NAME: google-java-format-1.11.0-all-deps.jar

      - name: Checkstyle
        run: |
          pushd scheduler
            mvn --no-transfer-progress jxr:jxr
            mvn --no-transfer-progress checkstyle:checkstyle
          popd

      - name: Publish Results on Pull Request
        run: |
          go run format_checkstyle.go